# Generated by Django 4.2 on 2024-11-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
